language: python
python:
  - "3.8"

# Customize this script to match your requirements
script:
  - echo "Running tests..."
  - pip install requests
  - pip install urllib3
  - python update_readme.py

# This section is important for badge generation
before_deploy:
  - git fetch --unshallow

deploy:
  provider: script
  script: echo "Deploying..."
  on:
    branch: main
